### ISSUE TITLE
New Icon: Mastodon

### ISSUE THREAD

**Issue by dana-ross** [Automattic/social-logos#67]
Press kit with logos available at https://joinmastodon.org/press-kit.zip

**Comment by timnolte** [comment]
@daveross since I'm going to be attempting to add Mastodon support to the Publicize module (pending WordPress.com can support it with the private code-base) I will need this in place. I've forked it and will be making this my first step since it'll hopefully be something attainable without needing to engage a WordPress.com developer.

**Comment by jeherve** [comment]
This was added in #115
