### ISSUE TITLE
PDFKit is rebuilding files

### ISSUE THREAD

**Issue by davewhitley** [Automattic/social-logos#93]
I tried to set up Social Logos on a fresh local copy, but when I ran the build command, all of the PDF were regenerated, even with no changes to the icons. I remebered this was similar to an issue on Gridicons

https://github.com/Automattic/gridicons/pull/304

I tried the fix that was discussed there, but it still regenerated the PDFs. The fix was to add `"pdfkit": "0.8.3"` to the packages folder. 

I tried checking all the relevant build files and compared them to the files on Gridicons, since they should ideally be almost identical.

After comparing a few of the new PDFs to the old ones, the only difference I see is that the file size is smaller. Maybe I should just commit the new changes to the PDFs?

Can someone clone a fresh copy of this repo following the install instructions and see what they get?

**Comment by folletto** [comment]
It could also be: https://github.com/Automattic/gridicons/pull/258 

I'm fairly sure that at some point I had to regenerate the full set and commit. After that it was just a matter of fixing the versions. The mismatch might come in any combination of `pdfkit` and `svg-to-pdfkit` and the latest run a specific setup had locally, and if it was pulled or updated. So it's possible, but also... kinda pointless to track it.

So I'd suggest to:
. Have a clean clone.
. Reproduce the build system versions to be identical to Gridicons.
. Merge the new set as comes out of it, after verifying that it reproduces always the same set every time it runs.

**Comment by drw158** [comment]
Inexplicably, I cloned a fresh copy, made sure the build system versions were identical to Gridicons, ran the build command... and no PDFs were changed. That's great, but now when I change an icon in the svg source folder and run the build command, nothing gets generated or updated. Not even the svg min folder. No errors as far as I can tell. I'll have to investigate later.

**Comment by noahtallen** [comment]
I'm reopening because I'm still having problems with PDFs :(

On current `trunk` branch:
- All (or most) PDFs regenerate locally
- Most PDFs are generated incorrectly, and can't be opened by PDF readers

I can fix the more important issue (invalid PDFs) by updating `pdfkit` and `svg-to-pdfkit`, but that means we get the issue where every PDF regenerates on run (due to the build system adding an "ID" to the PDF file.

Related: https://github.com/Automattic/gridicons/pull/310

I can't figure out why this is happening to me on `social-logos` but not in `gridicons`. Even after updating everything except the PDF packages in gridicons, all the PDFs work fine in `gridicons`. However, with an identical set of packages and gruntfile, PDFs fail here.

Since I need to move on with some other work, I'm going to land the change which updates pdfkits and re-introduces the problem where all PDFs are invalid. Hopefully we find a solution as a follow-up

**Comment by folletto** [comment]
I'm glad you found the fix :)

It's almost like I'm still there helping out ;)

**Comment by noahtallen** [comment]
Definitely <3
